### ISSUE TITLE
Custom Geocoder

### ISSUE THREAD

**Issue by nelsm** [Esri/information-lookup#20]
I tried setting the default geocoder to something other than ESRI's World Geocoder and it doesnt seem to stick and reverts back to it. Is there another location where it needs to be set besides the commonconfig.js? 
         

geocode: [{
                url: location.protocol + "//utility.arcgis.com/usrsvcs/servers/a88702314a8a48cb84d0a6305f1adcb6/rest/services/locators/RLIS_Locator/GeocodeServer"
            }]

**Comment by MikeMillerGIS** [comment]
You need to change the QueryForOrg to false in templateConfig.js, then add your GC to the helper service section in the default.js.

**Comment by nelsm** [comment]
Ok. Will do. Thanks for your help.

**Comment by Nataliya1** [comment]
I was just wondering if you was able to get this to work. I am having an issue with switching to custom geocoder as well. Thanks

**Comment by nelsm** [comment]
Unfortunately I was not able to switch to a custom geocoder.

**Comment by MikeMillerGIS** [comment]
Here are the steps to enabled custom geocoders.  This may not be needed with the most current version in github because the new configuration panel allows you to select which geocoders and layers you want to use for the search.   The locators need to be registered with your org.

1:  Open TemplateConfig.js and change queryForOrg to false
2:  Open Default.js and update the geocode section in helperServices

ex:
 "geocode": [{
        "url": "http://54.203.249.87/arcgis/rest/services/GasAssetLocator/GeocodeServer",
        "singleLineFieldName": "SingleLine",
        "placefinding": true

      }

**Comment by Nataliya1** [comment]
Mike,
I downloaded current version from github and my geocoder works! YAY! Thank you.

**Comment by MikeMillerGIS** [comment]
Closing the issue, please reopen or create a new one if you have more problems.
